### PR TITLE
Update moments-ago.vue

### PR DESCRIPTION
**Pull request by pcrombach**
Added 2 locals for Netherlands (nl) and Germany (de).

### CODE REVIEW

**Comment by pcrombach** [comment]
Accedentally changed " into '. I don't know how edit.

**Comment by jillztom** [comment]
Made some refactoring to the language options. Could you fix the conflict and then update the PR?

**Comment by pcrombach** [comment]
Hi, this is my first try to improve a npm module. I don’t know what you want me to do now. What conflict do I have to fix?

Verstuurd vanaf mijn iPad

**Comment by jillztom** [comment]
I refactored the code a bit. If you could take the latest commit from the master and then make changes to your code according to that. Then update this PR

**Comment by pcrombach** [comment]
Sorry,

I looked into it. I dom’t understand what you told me to do. I wish I could understand. Please help. Step-by-step.
I think I closed the request accedently, I think???

Try to guide me to request the change again………

Thanks in advance

**Comment by pcrombach** [comment]
Hi, I think I now understand what you were asking. Correct me if I’am wrong. You refactored the code after I pull the code for my changes. So I have to add my changes to your latest code. The changes you made make it more difficult to add the Dutch and German locals because the rules for 1  and many are not as simple as adding ‘s’.
Grammatically and syntactically the Dutch language is more complicated. If you want to make your code more simple for other languages I would made more arrays. I could make the changes but of course only if you want that. Also I would keep the prefix and the suffix managed in the code and not as a prop. They are also language dependent.

Before I found moments-ago.vue I had some code in my app to do this. Because I need a component like this one for more languages I make the changes for your code. If you don’t want to add these changes I consider to publish my forked version on npm.

Verstuurd vanaf mijn iPad

**Pull request closed without merging**
